# Generated by Django 6.0.6 on 2026-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('rainfall', models.FloatField(default=0.0, help_text='Rainfall in mm')),
                ('wind', models.FloatField(default=0.0, help_text='Wind speed')),
            ],
            options={
                'verbose_name': 'Weather Reading',
                'verbose_name_plural': 'Weather Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
