# Generated by Django 6.0.6 on 2026-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weatherobservation',
            new_name='weather_wea_station_438d82_idx',
            old_name='weather_wea_station_d883f3_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherobservation',
            new_name='weather_wea_timesta_a10d88_idx',
            old_name='weather_wea_timesta_1215fc_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherstation',
            new_name='weather_wea_code_853a1b_idx',
            old_name='weather_wea_code_4b9a11_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherstation',
            new_name='weather_wea_is_acti_8cff69_idx',
            old_name='weather_wea_is_acti_06ffb7_idx',
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='cloud_cover_pct',
            field=models.FloatField(blank=True, help_text='Cloud cover (%%).', null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='humidity_pct',
            field=models.FloatField(blank=True, help_text='Relative humidity (%%).', null=True),
        ),
    ]
