# Generated by Django 6.0.6 on 2026-09-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_i_status_85e429_idx',
            old_name='incidents_i_status_6ebcf9_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_i_inciden_337dba_idx',
            old_name='incidents_i_inciden_f6ff8b_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_i_start_t_eeaf33_idx',
            old_name='incidents_i_start_t_be44e2_idx',
        ),
    ]
